# Generated by Django 6.0 on 2026-01-01 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SubFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='apps.folder')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title', 'folder')},
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('categories', models.CharField(help_text='Comma-separated values (e.g. editor,image,ai)', max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='apps/icons/')),
                ('icon_url', models.URLField(blank=True, help_text='Optional external icon URL', null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('working', 'Working'), ('need_key', 'Needs API Key'), ('not_installed', 'Not Installed')], default='not_installed', max_length=20)),
                ('use', models.TextField(help_text='What this app is used for')),
                ('cost_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('folders', models.ManyToManyField(blank=True, related_name='apps', to='apps.folder')),
                ('sub_folder', models.ForeignKey(blank=True, help_text='Leave empty only if folder is "Other"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='apps.subfolder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
