# Generated by Django 6.0 on 2026-01-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_category_app_slug_remove_app_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='categories',
        ),
        migrations.AddField(
            model_name='app',
            name='categorys',
            field=models.ManyToManyField(blank=True, related_name='apps', to='apps.category'),
        ),
    ]
