# Generated by Django 6.0 on 2026-01-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_app_categories_app_categorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
