# Generated by Django 6.0 on 2026-01-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_app_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
