# Generated by Django 6.0 on 2026-01-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_app_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='categorys',
        ),
        migrations.AddField(
            model_name='app',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='apps', to='apps.category'),
        ),
    ]
