# Generated by Django 6.0 on 2026-01-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_remove_app_categorys_app_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='apps/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_font',
            field=models.CharField(blank=True, help_text='Optional use fa or bi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_url',
            field=models.URLField(blank=True, help_text='Optional external icon URL', null=True),
        ),
    ]
