# Generated by Django 6.0 on 2026-01-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_category_icon_category_icon_font_category_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='description',
            field=models.TextField(default="<p>  </p>    <p>  </p>    <div class='list-title'></div>     <ul class='list px-3'><li> </li>    <li> </li>      </ul>"),
        ),
        migrations.AlterField(
            model_name='app',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('need_key', 'Needs API Key'), ('not_installed', 'Not Installed')], default='need_key', max_length=20),
        ),
    ]
